### ISSUE TITLE
OCR not detecting anything

### ISSUE THREAD

**Issue by wwly23** [matt-m-o/YomiNinja#2] opened 2023-10-30 02:13 UTC
I installed it successfully (with all the various versions of the VC thing too) and there's a red border around the whole screen. When I press Alt + G (the hotkey I set it to. I don't remember if that's the default or not) the cursor freezes for a bit but the red border around the whole screen is unchanged and Japanese text isn't selected. I've got Yomichan set up. When there's Japanese text in my clipboard a little window pops up. I've tried various combinations for the OCR engine but nothing. It doesn't detect English either when I set it to English.

I'm on the latest version of Windows 11 with all the updates including the October 2023 feature update. manga_ocr works fine for me. I'm using a 4K screen and I tried HDR on and off too. RTX 4090 and Ryzen 7900X3D.

**Comment by matt-m-o** [comment] 2023-10-30 18:25
It's interesting that another user experienced a similar issue with an AMD Ryzen 7900X. I suspect there might be compatibility issues between OpenVino and AMD Ryzen 7000 series CPUs, as I've had no problems with AMD Ryzen 5000 series CPUs. I've tested on clean Windows 10 and 11 installs, and everything worked as expected.

Currently, OpenVino is the default choice due to its performance benefits, and I haven't encountered issues on my AMD CPUs. However, the next release will provide the option to use other runtimes, like ONNX.

Once it's confirmed what caused this problem, we can work on an automated solution to address this problem.

I will release a new version as soon as possible.
Thank you for providing some clues to solve this issue.

**Comment by matt-m-o** [comment] 2023-11-02 21:01
@wwly23
Try the [latest version](https://github.com/matt-m-o/YomiNinja/releases).
There's a new option called "Inference Runtime" in the "OCR Engine" section of the settings menu. Set it to "ONNX CPU," restart the OCR Engine, and let me know if this helps.

**Comment by wwly23** [comment] 2023-11-03 01:53
Nice, it works! Not sure if it's intended, but ONNX CPU also grabs all the English too.

**Comment by matt-m-o** [comment] 2023-11-03 19:44
Thanks, now I can understand better what's going on.
It's completely normal if it recognizes some Latin characters while set to another language.
You can stop the sniping tool from opening on PrintScreen key press in the Windows accessibility settings.
The use of PrintScreen is faster because it leverages Windows' native screenshot feature, which is highly optimized for obvious reasons. I might work on improving the speed of the custom hotkey in the future.

**Comment by matt-m-o** [comment] 2023-11-23 20:14
Please attempt to install [v0.3.1](https://github.com/matt-m-o/YomiNinja/releases/tag/v0.3.1).
This version should automatically configure the runtime to ONNX CPU, resolving the reported issue.

**Comment by wwly23** [comment] 2023-11-24 02:38
Hmm, ONNX CPU is selected when I opened v0.3.1 for the first time, but I'm not sure if my previous settings (ONNX CPU) were overwritten or not. I think they were.

Tenten stuff doesn't work for me though. Checking "Enable Yomi Ninja dictionary" spawns a blank black window on the top left screen. Option screens is a blank window with some clickable elements that are invisible. When I hover over text it shows a black window.

On another note, I tried messing with the option to disable click-through and felt it would maybe be more intuitive for at least an option for click-through to still work on non-OCR'd areas. Otherwise I have to alt-tab to do anything. A feature I'd like is selecting a region for the OCR. Could be a one time thing to grab text from a Twitter image or manga (press hotkey, select region, OCR only that region) or a more permanent region similar to how Game2Text works (press hotkey, select region within a selected window, auto-OCR that region perpetually for changes).

If any sound like good ideas I could make separate threads for them but just throwing out some ideas for now.

**Comment by matt-m-o** [comment] 2023-11-25 20:03
If ONNX is selected when opening for the first time, then the issue is considered resolved. 

Regarding [10ten](https://github.com/birchill/10ten-ja-reader/tree/main#usage), make sure to enable it by looking at the upper-right side of the application; there should be the 10ten toolbar button. Click on it to enable or disable it (black means enabled, and when it changes state the UI will be refreshed). It's the same button that appears on a web browser when 10ten is installed. 
![image](https://github.com/matt-m-o/YomiNinja/assets/25914763/d6a11eaa-5d41-48aa-b166-8e5a7ebbf08a)


The Yomi Ninja dictionary is still experimental, and you need to import a Yomichan dictionary for it to work. Otherwise, you'll only get a black pop-up.

Click-through functionality has been improved in the early access [version 0.4.0](https://www.patreon.com/posts/yomi-ninja-v0-4-93354858) and is much more intuitive now.

Thank you for the suggestions. I believe the features you described were already on the list of [planned features](https://github.com/matt-m-o/YomiNinja/tree/master#planned-features) and will likely be implemented soon, depending on Patreon supporters' priorities. Feel free to suggest other ideas you have.

**Closed** 2023-11-26 17:27 UTC
